server:
  port: 9999
  servlet:
    context-path: /

spring:
  datasource:
    username: root
    password: banana666
    url: jdbc:mysql://localhost:3306/bcms
  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.banana: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1

#  configuration:
#    call-setters-on-nulls: true